### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by bounteous-alisWard** [capacitor-community/screen-brightness#14] opened 2023-12-05 01:48 UTC
**Describe the bug**
This has been our top crash for a long time. Looking for advice if we need to repair on our end, or fix if needs to be repaired on your end.

```
com.elylucas.capscreenbrightness.ScreenBrightnessPlugin.lambda$setBrightness$0
java.lang.NullPointerException - Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
```

Android 7:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
       at com.elylucas.capscreenbrightness.ScreenBrightnessPlugin.lambda$setBrightness$0(ScreenBrightnessPlugin.java:22)
       at com.elylucas.capscreenbrightness.ScreenBrightnessPlugin$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6836)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

Android 14:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
       at com.elylucas.capscreenbrightness.ScreenBrightnessPlugin.lambda$setBrightness$0(ScreenBrightnessPlugin.java:22)
       at com.elylucas.capscreenbrightness.ScreenBrightnessPlugin$$ExternalSyntheticLambda0.run(:8)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8893)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**To Reproduce**
Unsure. We do have one screen with automatic screen brightness increased to max, and then we decrease it when you leave screen again, but I've never been able to produce this crash locally.

**Expected behavior**
No crash

**Smartphone (please complete the following information):**
- Device: Majority of crashes are on Samsung devices, though it occurs on other devices including Pixel.
 - OS: Android
 - Browser: N/A
 - Version: 
```
        "@capacitor-community/firebase-crashlytics": "^3.0.0",
        "@capacitor-community/http": "^1.4.1",
        "@capacitor-community/screen-brightness": "^5.0.0",
```

**Additional context**
ionic v7 (crash also observed with ionic 6), node & npm, angular (web)

41%
In background
0%
Rooted
100%
Proximity on

**Comment by bounteous-alisWard** [comment] 2023-12-05 01:55
Related crash with iOS. I say related, because it's not reporting setBrightness as the crash, but _userInfoForFileAndLine, after setBrightness. If interested:
```
Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                        0xec870 __exceptionPreprocess
1  libobjc.A.dylib                       0x2bc00 objc_exception_throw
2  Foundation                            0x6b6d18 _userInfoForFileAndLine
3  UIKitCore                             0xa2bef8 -[UISoftwareDimmingWindow setOverlayLevel:]
4  UIKitCore                             0xa2fe6c -[UIScreen setBrightness:]
5  CapacitorCommunityScreenBrightness    0x7478 (Missing UUID 5a1b0d8898563665a4768512ae8164cc)
6  CapacitorCommunityScreenBrightness    0x696c (Missing UUID 5a1b0d8898563665a4768512ae8164cc)
7  libdispatch.dylib                     0x26a8 _dispatch_call_block_and_release
8  libdispatch.dylib                     0x4300 _dispatch_client_callout
9  libdispatch.dylib                     0x12998 _dispatch_main_queue_drain
10 libdispatch.dylib                     0x125b0 _dispatch_main_queue_callback_4CF
11 CoreFoundation                        0x3720c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
12 CoreFoundation                        0x33f18 __CFRunLoopRun
```
Significantly, this one tells me: 94% In background.

Please let me know if I can provide any additional details to help get this fixed. Thank you!

**Comment by bounteous-alisWard** [comment] 2023-12-05 23:03
Hi there. Just adding more details. By a stroke of pure luck, I produced this on Android Pixel 6XL with Android 14. My actions were:

1. uninstall the app
2. fresh install the app
3. drag to home from drawer
4. launch the app from home screen
5. app crashed

But it's not every time, and I have tried 10x in a row to reproduce without success.

Device brightness is about 33%. Extra dim disabled. Bluetooth disabled. Internet and Location services on. Network was unthrottled. No instant permissions prompts for this app.

Log txt:
```Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
       at com.elylucas.capscreenbrightness.ScreenBrightnessPlugin.lambda$setBrightness$0(ScreenBrightnessPlugin.java:22)
       at com.elylucas.capscreenbrightness.ScreenBrightnessPlugin$$ExternalSyntheticLambda0.run(:8)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8177)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by andrerds** [comment] 2023-12-27 12:39
Hey! I'm experiencing the same issue on various types of devices and Android versions. Any updates on this?

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
       at com.elylucas.capscreenbrightness.ScreenBrightnessPlugin.lambda$setBrightness$0(ScreenBrightnessPlugin.java:22)
       at com.elylucas.capscreenbrightness.ScreenBrightnessPlugin$$ExternalSyntheticLambda0.run(:8)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by jcesarmobile** [comment] 2024-01-25 12:31
can you provide a sample app?

**Comment by jcesarmobile** [comment] 2024-04-18 12:16
closing due to the lack of reproduction

**Closed as not planned by jcesarmobile** 2024-04-18 12:16 UTC
